export const dataArr = [
  {
    id: '1',
    name: 'Order A',
    description: 'Fix broken pipe',
    signalPriority: 'HIGH',
    status: 'TODO',
    isNew: false,
  },
  {
    id: '2',
    name: 'Order B',
    description: 'Repair roof leak',
    signalPriority: 'MEDIUM',
    status: 'INPROGRESS',
    isNew: false,
  },
  {
    id: '3',
    name: 'Order C',
    description: 'Replace light bulb',
    signalPriority: 'LOW',
    status: 'DONE',
    isNew: false,
  },
  {
    id: '4',
    name: 'Order D',
    description: 'Inspect electrical wiring',
    signalPriority: 'HIGH',
    status: 'TODO',
    isNew: false,
  },
  {
    id: '5',
    name: 'Order E',
    description: 'Paint office walls',
    signalPriority: 'LOW',
    status: 'INPROGRESS',
    isNew: false,
  },
  {
    id: '6',
    name: 'Order F',
    description: 'Fix HVAC system',
    signalPriority: 'MEDIUM',
    status: 'DONE',
    isNew: false,
  },
  {
    id: '7',
    name: 'Order G',
    description: 'Clean water tank',
    signalPriority: 'HIGH',
    status: 'TODO',
    isNew: false,
  },
  {
    id: '8',
    name: 'Order H',
    description: 'Calibrate machinery',
    signalPriority: 'MEDIUM',
    status: 'INPROGRESS',
    isNew: false,
  },
  {
    id: '9',
    name: 'Order I',
    description: 'Check fire alarm system',
    signalPriority: 'HIGH',
    status: 'DONE',
    isNew: false,
  },
  {
    id: '10',
    name: 'Order J',
    description: 'Test backup generator',
    signalPriority: 'LOW',
    status: 'TODO',
    isNew: false,
  },
];
